-- METI™ SOURCES_QUEUE TABLE SCHEMA

CREATE TABLE IF NOT EXISTS public.sources_queue (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    processed boolean NOT NULL DEFAULT false,
    feature_collection jsonb NOT NULL,
    created_by uuid NULL,
    CONSTRAINT sources_queue_pkey PRIMARY KEY (id),
    CONSTRAINT sources_queue_created_by_fkey FOREIGN KEY (created_by)
        REFERENCES profiles (id)
) TABLESPACE pg_default;
